### ISSUE TITLE
rename to TuyaGateway

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/tuyagateway#70]
Protocol doesn't and shouldn't matter to the enduser
- package name
- images

**Comment by emontnemery** [comment]
I think protocol matters for DIY stuff like this, especially when it implements HomeAssistant's MQTT schemas.
Maybe TuyaGateway-MQTT could work to emphasize the gateway function?

Otherwise, at least MQTT should still be mentioned in the first paragraph in readme.md

**Comment by TradeFace** [comment]
It is mentioned in the first sentence :) I think MQTT scares new comers to home automation a bit. They don't know what it is. And many people don't get the pub/sub concept or how topics work. To get them to use the software we at least should get a chance to explain it. Indeed the readme should do a better job explaining what problems it solves and subsequently how it is solved. (Why, how, what)
