### ISSUE TITLE
declass TuyaMQTT

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/tuyagateway#73]
There is no need for it to it to be a class.

**Comment by emontnemery** [comment]
I think it's nice to keep it as a class to allow potential integration in other projects or extensions. Or maybe I don't understand the idea?

**Comment by TradeFace** [comment]
I thought of it as a standalone server, doing it's thing in the background. But yes, it could be integrated. Maybe I can live with a class that doesn't really have to be one.
