### ISSUE TITLE
Install to Home Assistant

### ISSUE THREAD

**Issue by Shaman2** [TradeFace/tuyagateway#81]
Hi. I did not quite understand how to install this gateway in the home assistant? Now I use home assistant as virtual machine in proxmox

Tuya Gateway is standalone or work with tuya smart application?

**Comment by TradeFace** [comment]
Tuya Gateway has no relation with tuya smart app. It connects directly to your tuya devices.

**Comment by Shaman2** [comment]
But first device need to connect to tuya smart apps for get localkey ?

**Comment by TradeFace** [comment]
https://github.com/TradeFace/gismocaster/wiki/Extract-Local-Key
