### ISSUE TITLE
[FR] - Dockerhub or Unraid app

### ISSUE THREAD

**Issue by jaburges** [TradeFace/tuyagateway#89]
Hi there,
Would it be possible to push this to dockerhub (make isnt a command available on Unraid).
Alternatively could you create an Unraid community App - info [here](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084)

Thanks

**Comment by TradeFace** [comment]
That has been in the planning for awhile #40. I don't have the time at the moment to get it done. I'm happy to merge you PR if you know how to do this.

**Comment by jaburges** [comment]
sure, i'll work on the unraid template.
You'll need to push the build to dockerhub though as I dont have access to your repo (plus not 100% how to do that)

**Comment by jaburges** [comment]
https://docs.docker.com/docker-hub/builds/
seems to be the dockerhub automated build process

**Comment by jaburges** [comment]
Couple of to-dos:
If you have a donation URL (patreon/paypal) LMK - i can add that to the template
Did you want to enable MQTT info (creds) as docker environment variables - then the user can add that info in the GUI (i added these variables in case of use)
Attached logo PNG 
![tuyagateway_logo](https://user-images.githubusercontent.com/14154875/93256118-b935a880-f74f-11ea-9a54-8efa3671baf6.png)

**Comment by TradeFace** [comment]
github has a workflow for dockerhub.... didn't look at it yet though, perhaps that is good starting point

**Comment by jaburges** [comment]
yeah the quickstart info is here:
https://docs.docker.com/docker-hub/

HTH

**Comment by TradeFace** [comment]
https://github.com/marketplace/actions/publish-docker

**Comment by TradeFace** [comment]
https://hub.docker.com/r/tradeface/tuyagateway

**Comment by travisterrell** [comment]
@jaburges Did you ever get this running in Unraid? If so, would you mind sharing configuration? 

I'm fairly familiar with Docker (am developer, have written a few build files), but way less familiar with Docker Compose or creating Unraid templates. I've been trying to translate the things in the example compose script to the template, and I think I have most of them (volumes, network mode, etc.) figured out, but some things from their example aren't as clear. 

For instance, what port(s) does tuyagateway itself need? I only see ports in the example for Mosquitto, HA, and gismocaster (presumably, I will have to create a separate container template in Unraid for gismocaster if desired). Also, why do they add a MySQL server in the second example? Did I miss this dependency somewhere in the docs? 

Thank you for any assistance you can provide!

**Comment by jaburges** [comment]
@travisterrell you can do this without waiting for the unraid template to publish.

At the bottom of the docker page select 'Add Container'

Name = tuyagateway (i like to avoid spaces as use the names in node-red)
Repository = tradeface/tuyagateway:latest
network Type = host

Then Click + Add another Path, Port, Variable, Label or Device

In the new window:
Config Type = Path
Name: Config
Container Path = /usr/src/app/config
Host Path = /mnt/user/appdata/tuyagateway (note this is for unraid typically - you can put this anywhere you want)

click add, then done
Ports arent needed as its using the host network to communicate, however it may conflict with other ports in use so be aware. 

The examples you are referring to are docker-compose.yml files. This is an easy and convenient way to spin up all the services you need that communicate (for example you could have a downloader docker-compose.yml that ran nzb, sonarr, radarr all on the same docker network and then a separate home automation docker-compose.yml)

With Unraid you dont need to use any of that, its all GUI driven for simplicity

**Comment by travisterrell** [comment]
Ah, so I basically had it figured out already and didn't know it! Thank you so much!

Are you also using gismocaster? If so, did you use a container for it as well? It looks like there's not an official one, though there are 2 from "mcblitz" and "juan11perez." I suppose I'll try out one of those, then perhaps make my own if that fails since it's a pretty simple one.

**Comment by jaburges** [comment]
you bet, glad it worked :)
i am not using gismocaster, but in this repo is a version https://github.com/TradeFace/gismocaster
