### ISSUE TITLE
Can't get brightness value on any device

### ISSUE THREAD

**Issue by tsightler** [TradeFace/tuyagateway#99]
Hi there.  I'm the current maintainer of tuya-mqtt which had gone stagnant due to the fact that I didn't have any Tuya devices, but I've recently acquire a few that are non-Tasmotizable and started to pick back up again.  Interestingly, I had started down a very similar path, with the goal to simplify the configuration, get rid of topic based configuration, implement some automatic device discovery and Home Assistant MQTT auto discovery, the primary difference was a plan to use the output from `tuya-cli wizard` as the primary config for devices (for simple devices like switches/sockets/dimmers/lights, that file alone could be used unchanged).

However, I then ran across your project and found it to be very interesting and share many of the same goals and was considering that I might retire the tuya-mqtt code in it's current working state (it's still quite usable) and instead spend some effort trying to help with this project, which seems more active.  I spent tonight trying to get it working and found it easy enough to get the basics, had my lights and dimmer switch turning on/off and reporting state fairly quickly.

Unfortunately, that was the end of my success and I'm not really sure why.  I wanted to start passing the brightness values for the dimmer and bulb, which seemed simple enough.  The dimmer uses a simple brightness scale of 0-255, the bulb 10-1000, but I can't get either of these to actually send a status, the brightness_state topic is always NULL and I just don't understand why.  When I run the gateway in debug I can see the DPS values being returned, but, value to the brightness_state topic is always null.  I assume I must be doing something wrong but the overall setup seems pretty simple.  Here's an example:

```
2020-09-24 01:12:18,762 DEBUG    (Thread-7) [tuyaface] (192.168.2.58) received msg (seq 0): [8:STATUS] rc: [0] payload: [{"dps":{"22":682},"t":1600924338}]
tuya/eba86a1731ac283b0eq8ix/20/state ON
2020-09-24 01:12:18,763 DEBUG    (Thread-7) [paho.mqtt.client] Sending PUBLISH (d0, q0, r0, m12), 'b'tuya/eba86a1731ac283b0eq8ix/20/state'', ... (2 bytes)
tuya/eba86a1731ac283b0eq8ix/22/brightness_state None
2020-09-24 01:12:18,764 DEBUG    (Thread-7) [paho.mqtt.client] Sending PUBLISH (d0, q0, r0, m13), 'b'tuya/eba86a1731ac283b0eq8ix/22/brightness_state'' (NULL payload)
tuya/eba86a1731ac283b0eq8ix/attributes {"20": true, "22": true}
2020-09-24 01:12:18,765 DEBUG    (Thread-7) [paho.mqtt.client] Sending PUBLISH (d0, q0, r0, m14), 'b'tuya/eba86a1731ac283b0eq8ix/attributes'', ... (24 bytes)
```

Can you help me understand what I'm missing?  See clearly that the brightness value (DPS 22) was returned as 682, but brightness value = None.

**Comment by TradeFace** [comment]
Looking through the code I realize that the code might be incomplete. In `tuyagateway/tuyagateway/transform/homeassistant.py` function `def get_publish_content(self):` only tries to map the device return data to a HA value. It doesn't seem to fallback to returning the original value if no mapping is found. 

I have the same issue on the limited devices, in fact I only have tuya switches.

**Comment by tsightler** [comment]
Ah, well that makes me feel a bit better.  If this were in JS I'd probably have seen that already but I'm still working on my ability to grok Python, so I have to climb that hill a little bit first, although I'm starting to put things together a little.  If I can get there I'll try to help because your project is already further along with the templating and configuration aspects using gismocaster (interestingly, I had also pursued a similar approach about a 2 years ago but found people kept killing their MQTT broker and losing all of their config, plus, my skills to create a web interface for configuration were quite lacking, so gave up that idea).

That being said, do you have any ability to transform data in this project?  Right now in the tuya-mqtt project I basically just give raw access to the DPS values (you can get/set any DPS value via Tuya style JSON or use some string commands/status to individual DPS topics), and I was building a simple JSON based template engine for mapping DPS topics to more Home Assistant friendly names.  However, I found that some things, like lights, seem to need more transformation to really be easily consumable by most home automation tools, for example it's difficult to get HA to work with the color format that Tuya uses for color/saturation, etc, without some manipulation.  I was thinking I'd have to write a color function to transform and map to the various DPS values of different bulbs.

**Comment by TradeFace** [comment]
Yeah, think I can put in that change in the next few days. 

Indeed I envisioned transformer functions for TG, but never came around implementing it.

**Comment by TradeFace** [comment]
Did a small update on dev branch. Pls check if that helps

**Comment by tsightler** [comment]
Well, I get a value now, but it's "true", which isn't exactly what you'd want when it should be a number from 1-255.  But that's a step up from no value.

**Comment by TradeFace** [comment]
Did you configure the field properly in GC? int or float value?

**Comment by tsightler** [comment]
It's configured as a int value, yes.  Do you have any examples of working gismo models with brightness, colors, etc?  So far I've only been able to use this with simple on/off devices, where it seems to work fine, and that's all the examples I've seen as well.

**Comment by TradeFace** [comment]
Nope I don't have examples. Can you listen for topic `tuyagateway/discovery/#` and paste the result here? To verify if the config message is send correctly.
